const COMPR_LINKS={chrome:"https://chromewebstore.google.com/detail/compr/opgdgckljdepjokbbdgahhbocdlkggkj",edge:"https://microsoftedge.microsoft.com/addons/detail/hiioneifjfpbgbnmmhjbhcnbbkpddnle"};
document.querySelectorAll(".store-link[data-store]").forEach(link=>{link.href=COMPR_LINKS[link.dataset.store];link.target="_blank";link.rel="noopener noreferrer"});
document.querySelectorAll("[data-year]").forEach(node=>node.textContent=new Date().getFullYear());

const COMPR_BETA={supabaseUrl:"https://taosgvfdnblnopaywimf.supabase.co",anonKey:"sb_publishable_cZtYQI3ApFTw8kU2a2AoBQ_nGdlSw1W",callbackUrl:"https://comprshop.github.io/compr-website/auth-callback.html"};
const betaForm=document.getElementById("betaAccessForm"),betaStatus=document.getElementById("betaAccessStatus");
document.querySelectorAll("[data-beta-plan]").forEach(link=>link.addEventListener("click",()=>{const input=document.querySelector(`input[name="plan"][value="${link.dataset.betaPlan}"]`);if(input)input.checked=true;}));
const requestedPlan=new URLSearchParams(location.search).get("plan");
if(["pro","ultimate"].includes(requestedPlan)){const input=document.querySelector(`input[name="plan"][value="${requestedPlan}"]`);if(input)input.checked=true;}
if(betaForm)betaForm.addEventListener("submit",async event=>{event.preventDefault();const button=betaForm.querySelector("button"),email=betaForm.email.value.trim(),plan=new FormData(betaForm).get("plan");button.disabled=true;betaStatus.textContent="Registering your interest…";try{localStorage.setItem("compr-founding-interest",JSON.stringify({plan,source:"website",savedAt:Date.now()}));const response=await fetch(`${COMPR_BETA.supabaseUrl}/auth/v1/otp`,{method:"POST",headers:{apikey:COMPR_BETA.anonKey,"Content-Type":"application/json"},body:JSON.stringify({email,create_user:true,redirect_to:COMPR_BETA.callbackUrl,data:{beta_interest:true,beta_plan:plan,beta_source:"website",founding_interest:true}})});if(!response.ok)throw new Error("signup_failed");betaForm.reset();betaStatus.textContent="Check your email to confirm your free COMPR account and Founding Access interest. No payment has been created and no numbered place is reserved yet.";}catch{localStorage.removeItem("compr-founding-interest");betaStatus.textContent="We couldn't register you just now. Please try again later.";}finally{button.disabled=false;}});

document.querySelectorAll(".faq-list button").forEach(button=>button.addEventListener("click",()=>{const article=button.closest("article"),answer=article.querySelector(".faq-answer"),open=button.getAttribute("aria-expanded")==="true";button.setAttribute("aria-expanded",String(!open));answer.hidden=open}));

const observer="IntersectionObserver" in window?new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}}),{threshold:.12}):null;
document.querySelectorAll(".reveal").forEach(node=>observer?observer.observe(node):node.classList.add("is-visible"));

const translations={
  en:{"The current video shows how products are saved and compared. Find This Cheaper is demonstrated separately above.":"See how COMPR fits into your shopping flow, keeps useful product details together and prepares products for comparison."},
  nl:{"How it works":"Zo werkt het","Find This Cheaper":"Vind dit goedkoper","Compare":"Vergelijken","Privacy":"Privacy","FAQ":"Vragen","Add to Chrome — Free":"Toevoegen aan Chrome — Gratis","Shop smarter with COMPR":"Shop slimmer met COMPR","Found something you want?":"Iets gevonden dat je wilt?","Find it cheaper.":"Vind het goedkoper.","COMPR checks for the same product at a better price — without leaving your shopping flow.":"COMPR controleert of hetzelfde product ergens goedkoper is, zonder je winkelritme te onderbreken.","See how it works":"Bekijk hoe het werkt","Free to install · No account required":"Gratis te installeren · Geen account nodig","Same product.":"Hetzelfde product.","Better price.":"Betere prijs.","Not something similar.":"Niet iets vergelijkbaars.","The same product.":"Hetzelfde product.","Check before you buy.":"Controleer voordat je koopt.","Shop normally":"Shop zoals altijd","Choose the better deal":"Kies de betere deal","Save & Compare":"Bewaar & vergelijk","Still deciding?":"Nog aan het kiezen?","Save it and compare.":"Bewaar en vergelijk.","One more check before you buy":"Nog één controle voor je koopt","Discounts, without the clutter.":"Kortingen, zonder de rommel.","Simple to use. Careful with your data.":"Eenvoudig te gebruiken. Zorgvuldig met je gegevens.","Frequently asked questions":"Veelgestelde vragen","Good to know before you install.":"Handig om te weten voor installatie.","Find it. Check it. Pay less.":"Vind het. Controleer het. Betaal minder."},
  de:{"How it works":"So funktioniert es","Find This Cheaper":"Günstiger finden","Compare":"Vergleichen","Privacy":"Datenschutz","FAQ":"Fragen","Add to Chrome — Free":"Für Chrome — kostenlos","Shop smarter with COMPR":"Cleverer shoppen mit COMPR","Found something you want?":"Etwas gefunden, das du willst?","Find it cheaper.":"Finde es günstiger.","See how it works":"So funktioniert es","Check before you buy.":"Vor dem Kauf prüfen.","Same product.":"Gleiches Produkt.","Better price.":"Besserer Preis.","Not something similar.":"Nicht etwas Ähnliches.","The same product.":"Dasselbe Produkt.","Find it. Check it. Pay less.":"Finden. Prüfen. Weniger zahlen."},
  fr:{"How it works":"Comment ça marche","Find This Cheaper":"Trouver moins cher","Compare":"Comparer","Privacy":"Confidentialité","FAQ":"Questions","Add to Chrome — Free":"Ajouter à Chrome — gratuit","Shop smarter with COMPR":"Achetez plus malin avec COMPR","Found something you want?":"Vous avez trouvé ce que vous voulez ?","Find it cheaper.":"Trouvez-le moins cher.","See how it works":"Voir comment ça marche","Check before you buy.":"Vérifiez avant d’acheter.","Same product.":"Même produit.","Better price.":"Meilleur prix.","Not something similar.":"Pas un produit similaire.","The same product.":"Le même produit.","Find it. Check it. Pay less.":"Trouvez. Vérifiez. Payez moins."}
};

const translatable=[...document.querySelectorAll("h1,h2,h3,p,a,button,li,strong,span,figcaption")].filter(node=>!node.children.length);
translatable.forEach(node=>node.dataset.original=node.textContent.trim());
function setLanguage(code){const language=["en","nl","de","fr"].includes(code)?code:"en",map=translations[language]||{};translatable.forEach(node=>{const original=node.dataset.original;if(original)node.textContent=map[original]||original});document.documentElement.lang=language;document.querySelectorAll("[data-language-select]").forEach(select=>select.value=language);localStorage.setItem("compr-language",language);document.querySelectorAll("video").forEach(video=>Array.from(video.textTracks).forEach(track=>track.mode=track.language===language?"showing":"disabled"))}
document.querySelectorAll("[data-language-select]").forEach(select=>select.addEventListener("change",()=>setLanguage(select.value)));
setLanguage(localStorage.getItem("compr-language")||"en");
